apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payment-gateway
  labels:
    app: payment-gateway
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: payment-gateway:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "v1"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  strategy:
    blueGreen:
      activeService: payment-gateway-active
      previewService: payment-gateway-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
