apiVersion: v1
kind: Service
metadata:
  name: order-service-canary
  labels:
    app: order-service-canary
spec:
  selector:
    app: order-service-canary
  ports:
    - port: 80
      targetPort: 8000
      name: http
