apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "v3"
            - name: INJECT_FAILURE
              value: "true"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  strategy:
    blueGreen:
      activeService: order-service-active
      previewService: order-service-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
          - templateName: error-rate-check
        args:
          - name: service-name
            value: order-service-preview
